package com.guanyu.haigui.service;

import com.guanyu.haigui.pojo.model.UserInfo;
import com.guanyu.haigui.repository.UserInfoRepository;
import com.guanyu.haigui.utils.UsernameUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

@Service
@RequiredArgsConstructor
public class WechatProfileSyncService {

    private final UserInfoRepository userInfoRepository;

    /**
     * 微信原生账号（无密码）是否仍需补全：占位用户名 wx_* 或未设置头像。
     */
    public static boolean needsProfileSetup(UserInfo user) {
        if (user == null || StringUtils.hasText(user.getPassword())) {
            return false;
        }
        boolean usernamePending = UsernameUtils.isAutoGeneratedWechatUsername(user.getUsername());
        boolean avatarMissing = !StringUtils.hasText(user.getAvatar());
        return usernamePending || avatarMissing;
    }
}
