package com.guanyu.haigui.utils;

import com.guanyu.haigui.Exception.BusinessException;
import org.springframework.util.StringUtils;

import java.util.regex.Pattern;

public final class UsernameUtils {

    private static final Pattern USERNAME_PATTERN = Pattern.compile("^[a-zA-Z0-9_]{3,20}$");

    private UsernameUtils() {
    }

    public static String normalize(String username) {
        return username != null ? username.trim() : "";
    }

    public static String validateForRegister(String username) {
        String trimmed = normalize(username);
        if (!StringUtils.hasText(trimmed)) {
            throw new BusinessException(400, "用户名不能为空");
        }
        if (trimmed.length() < 3 || trimmed.length() > 20) {
            throw new BusinessException(400, "用户名长度需为 3～20 个字符");
        }
        if (!USERNAME_PATTERN.matcher(trimmed).matches()) {
            throw new BusinessException(400, "用户名仅支持字母、数字和下划线");
        }
        if (trimmed.startsWith("wx_")) {
            throw new BusinessException(400, "请换一个用户名");
        }
        return trimmed;
    }

    /** 微信注册时系统自动生成的占位用户名 */
    public static boolean isAutoGeneratedWechatUsername(String username) {
        return StringUtils.hasText(username) && username.startsWith("wx_");
    }
}
